---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
  # name: applications
  # labels:
    # gitops.tier.layer: applications
# spec:
  # sourceRepos:
  # - '*'
  # destinations:
  # - namespace: '*'
    # server: '*'
  # clusterResourceWhitelist:
  # - group: '*'
    # kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-dr
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://c111-e.us-east.containers.cloud.ibm.com:31784
  project: default
  source: # repoURL  and targetRevision populated by kustomize patches in 3-apps/kustomization.yaml
    path: 3-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      

---
apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: hello-app-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-C49KZH
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.2.0-r1
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/hello-app-rest:5f2d3a2e3298b203f1b8f97ab688f9b77e6abab2
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml