apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-2
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://c111-e.us-east.containers.cloud.ibm.com:31784
  project: default
  source: # repoURL  and targetRevision populated by kustomize patches in 3-apps/kustomization.yaml
    repoURL: https://github.com/iiab-mw-gitops/dr-cluster-gitops.git
    targetRevision: master
    path: 3-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
